server:
  port: ${PORT:8080}

spring:
  application:
    name: backend
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME:}
    password: ${SPRING_DATASOURCE_PASSWORD:}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        physical_naming_strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit_naming_strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${CLERK_ISSUER_URI:https://premium-caiman-41.clerk.accounts.dev}
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

clerk:
  publishable-key: ${NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
  secret-key: ${CLERK_SECRET_KEY}
